# Generated by Django 5.2.7 on 2026-02-07 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=50)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
            ],
            options={
                'db_table': 'expense_account',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'expense_book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book_id', models.UUIDField(db_index=True)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'expense_category',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'expense_paymentmode',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('book_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('category_id', models.UUIDField(db_index=True)),
                ('payment_mode_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'expense_transaction',
            },
        ),
    ]
