# Generated by Django 4.2.9
# UniqueConstraint (device_id, app_id) for offline-first UUID sync

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_account_app_id_book_app_id_category_app_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(
                fields=['device_id', 'app_id'],
                name='unique_book_device_appid'
            ),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(
                fields=['device_id', 'app_id'],
                name='unique_account_device_appid'
            ),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                fields=['device_id', 'app_id'],
                name='unique_category_device_appid'
            ),
        ),
        migrations.AddConstraint(
            model_name='paymentmode',
            constraint=models.UniqueConstraint(
                fields=['device_id', 'app_id'],
                name='unique_paymentmode_device_appid'
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(
                fields=['device_id', 'app_id'],
                name='unique_transaction_device_appid'
            ),
        ),
    ]
